class FIELDS:
    DENTISTA = "DENTISTA"                           # Dentistas
    SEMANA = "SEMANA"                               # Link to Semana
    TRATAMIENTOS = "TRATAMIENTOS"                   # link to tratamiento
    COBROS = "COBROS"                               # link to cobros
    FECHA = "FECHA"                                 # YYYY-MM-DD
    PACIENTES = "PACIENTES"                         # link to pacientes
    AUTONUMERO = "AUTONUMERO"                       # Autogenerated
    CONSULTA_ID = "CONSULTA_ID"                     # Autogenerated
    TOTAL_COBRO = "TOTAL_COBRO"                     # Autogenerated
    PAGOS_DENTISTAS = "PAGOS_DENTISTAS"             # link to PAGO DENTISTAS
    MONTO_PAGOS_DENTISTAS = "MONTO_PAGOS_DENTISTAS" #Autgenerated

