# FIELDS TABLE
class FIELD:
    FECHA = "FECHA"             # YYYY-MM-DD
    CUENTA = "CUENTA"           # CUENTA BANCARIA
    CONSULTAS = "CONSULTAS"     # link to CONSULTAS TABLE
    MONTO = "MONTO"             # MONTO
    TRATAMIENTO = "TRATAMIENTO" # AUTOGENERATED: link to to TRATAMIENTO (este link es autogenerado a partir de CONSULTAS)
    COBRO_ID = "COBRO_ID"       # AUTOGENERATED:  "${MONTO} - {CUENTA} - {FECHA}-ID"
    ESTATUS = "ESTATUS"         # ESTATUS
    FACTURA = "FACTURA"         # FACTURA
    SEMANA  = "SEMANA"          # SEMANA LINK
