# FACTURA_3_3


# factura 3.3 elements
FACTURA_3_3_RECEPTOR = "Receptor"
FACTURA_3_3_COMPLEMENTO = "Complemento"
FACTURA_3_3_COMPLEMENTO_CFDI_REGISTRO_FISCAL = "CFDIRegistroFiscal"
FACTURA_3_3_TIMBRE_FISCAL_DIGITAL = "TimbreFiscalDigital"

# factura 3.3 fields
FACTURA_3_3_RFC = "Rfc"
FACTURA_3_3_NAME = "Nombre"
FACTURA_3_3_REGIMEN_FISCAL = "RegimenFiscal"
FACTURA_3_3_UUID = "UUID"
