# FIELD DATA
class FIELDS:
    APELLIDOS = "APELLIDOS"
    CONSULTAS = "CONSULTAS"
    TELEFONO = "TELEFONO"
    NAME = "NOMBRE"
    PACIENTE_ID = "PACIENTE_ID"
    BADGE_ID = "BADGE_ID"
    CORREO = "CORREO"

