
# ENV variables
AIRTABLE_API_KEY = "AIRTABLE_API_KEY"
CONSULTORIO_2022_BASE_ID_AIR_TABLE = "CONSULTORIO_2022_BASE_ID_AIR_TABLE"

# CONSULTAS TABLE
CONSULTAS_TABLE_NAME_AIR_TABLE = "CONSULTAS_TABLE_NAME_AIR_TABLE"

# REPORTE TABLE
REPORTE_TABLE_NAME_AIR_TABLE = "REPORTE_TABLE_NAME_AIR_TABLE"

# COBROS TABLE
COBROS_TABLE_NAME_AIR_TABLE = "COBROS_TABLE_NAME_AIR_TABLE"

# PAGOS DENTISTAS
PAGOS_DENTISTAS_TABLE_NAME_AIR_TABLE = "PAGOS_DENTISTAS_TABLE_NAME_AIR_TABLE"

# PACIENTES TABLE
PACIENTES_TABLE_AIR_TABLE = "PACIENTES_TABLE_AIR_TABLE"

# LISTA DE TRATAMIENTOS TABLE
LISTA_TRATAMIENTOS_AIR_TABLE = "LISTA_TRATAMIENTOS_AIR_TABLE"

# TRATAMIENTO TABLE
TRATAMIEMTO_TABLE_NAME_AIR_TABLE = "TRATAMIEMTO_TABLE_NAME_AIR_TABLE"

# DEFINE SINGLE VALUES
class VALID_CUENTAS_AIR_TABLE:
    BBVA = "BBVA"
    MERCADO_PAGO = "MERCADO PAGO"
    BBVA_HIRVIN = "BBVA HIRVIN"
    SANTANDER = "SANTANDER"
    EFECTIVO = "EFECTIVO"
    REAL_SOLARE = "REAL SOLARE"

VALID_CUENTAS_LIST = [VALID_CUENTAS_AIR_TABLE.BBVA,
                VALID_CUENTAS_AIR_TABLE.MERCADO_PAGO,
                VALID_CUENTAS_AIR_TABLE.BBVA_HIRVIN,
                VALID_CUENTAS_AIR_TABLE.SANTANDER,
                VALID_CUENTAS_AIR_TABLE.EFECTIVO,
                VALID_CUENTAS_AIR_TABLE.REAL_SOLARE]

class VALID_PAGOS_ESTATUS:
    PAGADO = "PAGADO"
    PENDIENTE = "PENDIENTE"
    CANCELADO = "CANCELADO"

PAGOS_ESTATUS_LIST =    [VALID_PAGOS_ESTATUS.PAGADO,
                        VALID_PAGOS_ESTATUS.PENDIENTE,
                        VALID_PAGOS_ESTATUS.CANCELADO]

class VALID_DENTISTAS_AIR_TABLE:
    DIANA = "DIANA"
    JENNY = "JENNY"
    VERO = "VERO"
    DANY = "DANY"
    GABY = "GABY"
    JULIO = "JULIO"
    BOSNIA = "BOSNIA"

DENTISTAS_LIST =    [VALID_DENTISTAS_AIR_TABLE.DIANA,
                    VALID_DENTISTAS_AIR_TABLE.JENNY,
                    VALID_DENTISTAS_AIR_TABLE.VERO,
                    VALID_DENTISTAS_AIR_TABLE.DANY,
                    VALID_DENTISTAS_AIR_TABLE.GABY,
                    VALID_DENTISTAS_AIR_TABLE.JULIO,
                    VALID_DENTISTAS_AIR_TABLE.BOSNIA]

class VALID_FACTURA_STATUS:
    PENDIENTE = "PENDIENTE"
    ENTREGADA = "ENTREGADA"
    CANCELADA = "CANCELADA"
    SIN_FACTURA = "SIN FACTURA"

FACTURA_STATUS_LIST = [VALID_FACTURA_STATUS.SIN_FACTURA,
                        VALID_FACTURA_STATUS.PENDIENTE,
                        VALID_FACTURA_STATUS.ENTREGADA,
                        VALID_FACTURA_STATUS.CANCELADA]