# CONST
MONTHS_DICT = {1:"ENERO", 2:"FEBRERO", 3:"MARZO", 4:"ABRIL", 5:"MAYO", 6:"JUNIO", 7:"JULIO", 8:"AGOSTO", 9:"SEPTIEMBRE", 10:"OCTUBRE", 11:"NOVIEMBRE", 12:"DICIEMBRE"}

# MODES
LIST_MODE = "LIST_MODE"
DATE_PICKER = "DATE_PICKER"
DINAMIC_LIST = "DINAMIC_LIST"
DINAMIC_LIST_AIR = "DINAMIC_LIST_AIR"
CONFIRM_PICKER = "CONFIRM_PICKER"
FLOAT_NUMBER = "FLOAT_NUMBER"
INT_NUMBER = "INT_NUMBER"
STR_BOX = "STR_BOX"
PHONE_NUMBER = "PHONE_NUMBER"

# CONSULTA ESTATE MACHINE
GET_CONSULTA_DATE_ST= "GET_CONSULTA_DATE"
GET_PACIENTE_ID_ST = "GET_PACIENTE_ID"
GET_DENTISTA_ID_ST = "GET_DENTISTA_ID_ST"
GET_CONSULTA_NEW_COBRO = "GET_CONSULTA_NEW_COBRO"
GET_CONSULTA_NEW_PAGO = "GET_CONSULTA_NEW_PAGO"
GET_CONSULTA_EXIT_CONFIRMATION = "GET_CONSULTA_EXIT_CONFIRMATION"

# PAGOS_DENTISTAS ESTATE MACHINE
GET_PAGOS_DATE_ST = "GET_PAGOS_DATE_ST"
GET_PAGOS_MONTO_ST = "GET_PAGOS_MONTO_ST"
GET_PAGOS_CUENTA_ST = "GET_PAGOS_CUENTA_ST"
GET_PAGOS_ESTATUS_ST = "GET_PAGOS_ESTATUS_ST"
GET_PAGOS_EXIT_CONFIRMATION = "GET_PAGOS_EXIT_CONFIRMATION"

# COBROS ESTATE MACHINE
GET_COBROS_DATE_ST = "GET_COBROS_DATE_ST"
GET_COBROS_MONTO_ST = "GET_COBROS_MONTO_ST"
GET_COBROS_CUENTA_ST = "GET_COBROS_CUENTA_ST"
GET_COBROS_ESTATUS_ST = "GET_COBROS_ESTATUS_ST"
GET_COBROS_FACTURA_ST =  "GET_COBROS_FACTURA_ST"
GET_COBROS_EXIT_CONFIRMATION = "GET_COBROS_EXIT_CONFIRMATION"

# STATES TYPES
STATE_TYPE_BASE = "STATE_TYPE_BASE"
STATE_TYPE_EXIT_CONFIRMATION = "STATE_TYPE_EXIT_CONFIRMATION"
STATE_TYPE_NEW_MACHINE = "STATE_TYPE_NEW_MACHINE"

