# FIELDS TABLE
class FIELD:
    TRATAMIENTO = "TRATAMIENTO"             # YYYY-MM-DD
    CANTIDAD = "CANTIDAD"           # CUENTA BANCARIA
    COSTO_FINAL = "COSTO_FINAL"     # link to CONSULTAS TABLE
